DROP TABLE IF EXISTS Accounts;
CREATE TABLE IF NOT EXISTS Accounts(
id INTEGER PRIMARY KEY AUTOINCREMENT,
iban CHAR(29) UNIQUE,
currency CHAR(3),
balance FLOAT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
;

DROP TABLE IF EXISTS Customers;
CREATE TABLE IF NOT EXISTS Customers(
id INTEGER PRIMARY KEY AUTOINCREMENT,
first_name VARCHAR,
last_name VARCHAR,
phone INTEGER UNIQUE,
is_active INT(1) NOT NULL DEFAULT 1,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
account_id INTEGER,
FOREIGN KEY(account_id) REFERENCES Accounts(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Transactions;
CREATE TABLE IF NOT EXISTS Transactions(
id INTEGER PRIMARY KEY AUTOINCREMENT,
amount FLOAT,
type CHAR(2),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
description VARCHAR(160),
account_id INTEGER,
FOREIGN KEY(account_id) REFERENCES Accounts(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Cards;
CREATE TABLE IF NOT EXISTS Cards(
id INTEGER PRIMARY KEY AUTOINCREMENT,
type CHAR(2),
number CHAR(16) UNIQUE,
expires_at TIMESTAMP DEFAULT (DATE('now','+3 years')),
pin_code INTEGER(4),
cvv2 INTEGER(3),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
account_id INTEGER,
currency CHAR(3),
FOREIGN KEY(account_id) REFERENCES Accounts(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);